config/routes.rb
CoreConsumer::Application.routes.draw do
  
  root :to => "home#index"

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  enum role: [:admin, :user, :manager, :report, :forecast, :deploy]
  
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "Access denied."
    redirect_to (request.referrer || root_path)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?
  skip_before_filter :require_no_authentication  # Lets me add users as admin

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized, except: [:show]

  def index
    @users = User.all
    authorize @users
  end
  
  def new
    @user = User.new
    authorize @user
  end
  
  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end
  
  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
  
  protected
  
  def build_resource(hash=nil)
    hash ||= resource_params || {}
    self.resource = resource_class.new_with_session(hash, session)
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h3>Home</h3>

<div class="container-fluid">
  <div class="row">
  
  I am Home!
  
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="span12 text-center">
      <%= content_tag :div, msg, :class => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <li><%= link_to 'Home', root_path, class: 'navbar-brand' %></li>
    </div>
    <div class="">
      <ul class="navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete', class: 'navbar-brand' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path, class: 'navbar-brand' %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit User', edit_user_registration_path, class: 'navbar-brand' %></li>
<% else %>
  <li><%= link_to 'Sign Up', new_user_registration_path, class: 'navbar-brand' %></li>
<% end %>
<% if user_signed_in? and current_user.admin?%>
  <!-- <li><%= link_to 'Add User', new_user_path, class: 'navbar-brand' %></li> -->
  <li><%= link_to 'List Users', users_path, class: 'navbar-brand' %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CoreConsumer" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "CoreConsumer" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/users/edit.html.erb
<h3>Edit: <%= @user.email %></h3>

<%= form_for @user do |f| %>

  <p><%= f.label :name %><br />
  <%= f.text_field :name %></p>
  
  <div><%= f.label :email %><br />
  <%= f.email_field :email %></div>

  <div><%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
  <%= f.password_field :password, :autocomplete => "off" %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

  <div><%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
  <%= f.password_field :current_password %></div>
  
  <div><%= f.submit "Update" %></div>
<% end %>

<%= link_to "Back", :back %>

app/views/users/index.html.erb
<h3>Users</h3>

<div class="container-fluid">
  <div class="row">

  <% if !current_user.nil? and current_user.admin? %>
  
    <table class="table table-hover table-bordered table-condensed table-striped">
    <thead>
      <tr>
          <th class="col-sm-2">User</th>
          <th class="col-sm-2">Name</th>
          <th class="col-sm-4">Role</th>
          <th class="col-sm-8">Action</th>
        </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.email, user %> </td>
          <td><%= user.name %></td>
          <td>
            <%= form_for(user) do |f| %>
              <%= f.select(:role, User.roles.keys.map {|role| [role,role]}) %>
              <%= f.submit 'Change Role', :class => 'btn-xs btn-link' %>
            <% end %>
          </td>
          <td>
            <%= link_to t('.edit'), edit_user_path(user) %>
            <%= link_to("Delete", user_path(user), :data => { :confirm => "Delete User: #{user.email}?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
          </td>
        </tr>
      <% end %>
    </tbody>
    </table>
  <% end %>

  </div>
</div>

app/views/users/new.html.erb
<h2>Add User</h2>

<%= form_for @user do |f| %>
  <p><%= f.label :name %><br />
  <%= f.text_field :name %></p>
  
  <div><%= f.label :email %><br />
  <%= f.email_field :email %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

  <div><%= f.submit "Sign up" %></div>
 <% end %>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>